<a href="https://colab.research.google.com/github/sonuuno2020/CNN/blob/main/00_fundamental_of_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to fundamentals of tensors using tensorflow**

* Introduction to tensors
* Getting started with tensors
* Manipulating tensors
* Tensors and NumPy
* tf.function to speed up python function
* Using GPU with tensorflow

## **Introduction to tensors**

In [ ]:
import tensorflow as tf

print(tf.__version__)

2.7.0


In [ ]:
scaler=tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scaler.ndim

0

* tensor with `rank 0`

In [ ]:
vector=tf.constant([1])
vector

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>

In [ ]:
vector.ndim

1

* tensor with `rank 1`

In [ ]:
vector2=tf.constant([1,3])
vector2

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

In [ ]:
vector2.ndim

1

In [ ]:
vector3=tf.constant([[1,34],[22,3]])
vector3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1, 34],
       [22,  3]], dtype=int32)>

In [ ]:
vector3.ndim

2

* tensor with `rank 2`

In [ ]:
tensor=tf.constant([[[11,22,33],[1,2,3]]])
tensor

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[11, 22, 33],
        [ 1,  2,  3]]], dtype=int32)>

In [ ]:
tensor.ndim

3

* tensor with `rank 3`

### **Creating Tensors by `tf.Variable()`**

In [ ]:
changeable=tf.Variable([3,5])
Unchangeable=tf.constant([10,10])

changeable,Unchangeable

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 5], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [ ]:
changeable[0]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
changeable[0].assign(33)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([33,  5], dtype=int32)>

In [ ]:
changeable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([33,  5], dtype=int32)>

In [ ]:
Unchangeable[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
Unchangeable[0]=9

TypeError: ignored

In [ ]:
Unchangeable[0].assign(33)

🔑 **Thing to note here is that we can't change a tensor which is created using `tf.constant()` as it's name tells, but we can change a tensor which is created by `tf.Variable()`**

### Creating random tensors

* random tensors are tensor with arbitary size and random numbers.

In [ ]:
random1=tf.random.Generator.from_seed(42)
random1=random1.normal(shape=(3,2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random2=tf.random.Generator.from_seed(422)
random2.state

<tf.Variable 'Variable:0' shape=(3,) dtype=int64, numpy=array([422,   0,   0])>

In [ ]:
tf.random.uniform([2,5,3],minval=10,maxval=20)

<tf.Tensor: shape=(2, 5, 3), dtype=float32, numpy=
array([[[16.878912 , 14.844789 , 19.309944 ],
        [12.52187  , 17.311539 , 18.925682 ],
        [19.467484 , 17.493341 , 13.492563 ],
        [15.471826 , 12.616039 , 16.973433 ],
        [11.196259 , 15.348434 , 17.148968 ]],

       [[18.750177 , 13.3967495, 11.737762 ],
        [14.418521 , 19.00826  , 11.380386 ],
        [11.221798 , 15.754491 , 19.417181 ],
        [19.186584 , 15.970848 , 16.109482 ],
        [18.208626 , 18.326979 , 18.915848 ]]], dtype=float32)>

### Shuffle tensors

In [ ]:
## shuffling of tensors is done for clustering of similar type of data
random4=tf.constant([[12,4],[54,7],[56,11],[22,33]])
tf.random.shuffle(random4)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[12,  4],
       [22, 33],
       [54,  7],
       [56, 11]], dtype=int32)>

* shuffle accross first dimension of tensor

In [ ]:
## using `set_seed()`

tf.random.set_seed(42) # global level seed
random4=tf.constant([[12,4],[54,7],[56,11],[22,33]])
tf.random.shuffle(random4,seed=90),tf.random.shuffle(random4),tf.random.shuffle(random4,seed=42) # operational level seed

(<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[12,  4],
        [54,  7],
        [22, 33],
        [56, 11]], dtype=int32)>, <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[22, 33],
        [12,  4],
        [54,  7],
        [56, 11]], dtype=int32)>, <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[54,  7],
        [56, 11],
        [12,  4],
        [22, 33]], dtype=int32)>)

* when we use both we get same result always.

In [ ]:
tf.random.shuffle(random4,seed=90) # opreational level seed

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[54,  7],
       [12,  4],
       [56, 11],
       [22, 33]], dtype=int32)>

* each time we get different result

In [ ]:
tf.random.set_seed(42) # global level seed
tf.random.shuffle(random4)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[22, 33],
       [12,  4],
       [54,  7],
       [56, 11]], dtype=int32)>

* each time we get same result

### Other ways to create tenosrs

`tf.ones()` and `tf.zeros()`

In [ ]:
tf.ones([9,10],dtype='int32')

<tf.Tensor: shape=(9, 10), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>

In [ ]:
tf.zeros([4,5])

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

`Using NumPy`

In [ ]:
import numpy as np

In [ ]:
ones=np.ones(10)

In [ ]:
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
tf.constant(ones)

<tf.Tensor: shape=(10,), dtype=float64, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])>

numpy array are converted into tensors , As GPU compute tenosr faster.

In [ ]:
temp=tf.constant(ones,shape=(2,5))

In [ ]:
temp

<tf.Tensor: shape=(2, 5), dtype=float64, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])>

## **Geting information about Tensors**

1. shape
2. Rank
3. Axis or dimension
4. size

In [ ]:
tf.size(temp)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
zeros=tf.zeros(shape=[2,3,4,5])
zeros

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
zeros.ndim

4

In [ ]:
tf.size(zeros)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [ ]:
zeros.shape

TensorShape([2, 3, 4, 5])

In [ ]:
zeros[:,:,:,:3]

<tf.Tensor: shape=(2, 3, 4, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

### * **`tf.expand_dims()`**

axis=0 : add an axis to left side of shape array.

axis=1 : add axis to right of leftmost of shape array.

axis=-1 : add an asix to right side of shape array.

In [ ]:
tf.expand_dims(zeros,axis=0)

<tf.Tensor: shape=(1, 2, 3, 4, 5), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]]], dtype=float32)>

## **Manipulating Tensors**

### **Basic operations**

In [ ]:
tensor=tf.constant([[2,4],[5,7]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 14],
       [15, 17]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 7]], dtype=int32)>

In [ ]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 40],
       [50, 70]], dtype=int32)>

In [ ]:
tensor//2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3]], dtype=int32)>

In [ ]:
tf.multiply(tensor,70)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[140, 280],
       [350, 490]], dtype=int32)>

### **matrix multiplication**

In [ ]:
# `tf.matmul()`
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[24, 36],
       [45, 69]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 7]], dtype=int32)>

In [ ]:
# matrix multn with python operator `@`

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[24, 36],
       [45, 69]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
X=tf.constant([[1,2],
               [3,4],
               [5,6]])

Y=tf.constant([[11,22],
               [33,44],
               [55,66]])

In [ ]:
X @ Y

InvalidArgumentError: ignored

*shape incompatiable for matrix multiplication*

In [ ]:
X @ tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 99, 132, 165],
       [209, 286, 363],
       [319, 440, 561]], dtype=int32)>

In [ ]:
X = tf.constant([[[ 1,  2,  3],
                  [ 4,  5,  6]],
                 [[ 7,  8,  9],
                  [10, 11, 12]]])

In [ ]:
tf.transpose(X)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]], dtype=int32)>

In [ ]:
tf.transpose(X,perm=[0,2,1]) # permutation of dimensions for transposed matrix ,
# here shape=[0th dim,2nd dim,1st dim] ( i.e shape[2,2,3]===>shape(2,3,2))

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  4],
        [ 2,  5],
        [ 3,  6]],

       [[ 7, 10],
        [ 8, 11],
        [ 9, 12]]], dtype=int32)>

In [ ]:
tf.transpose(X,perm=[2,1,0]) 

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]], dtype=int32)>

In [ ]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 22],
       [33, 44],
       [55, 66]], dtype=int32)>

In [ ]:
tf.transpose(Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 33, 55],
       [22, 44, 66]], dtype=int32)>

In [ ]:
tf.matmul(Y,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 605, 1331, 2057],
       [1331, 3025, 4719],
       [2057, 4719, 7381]], dtype=int32)>

### **changing datatype of tensor**

In [ ]:
B=tf.constant([1.2,3.5])
B.dtype

tf.float32

In [ ]:
C=tf.constant([1,2])
C.dtype

tf.int32

In [ ]:
D=tf.constant([3.5,6.4],dtype='float16')
D.dtype

tf.float16

* `cast()`

In [ ]:
E=tf.cast(B,dtype=tf.float16) # tf.float16 is same as 'float16'
E,E.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 3.5], dtype=float16)>,
 tf.float16)

In [ ]:
F=tf.cast(C,dtype=tf.float16)
F,F.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 2.], dtype=float16)>,
 tf.float16)

### **Aggregating Tensors**

aggregation = make cluster of things from multiple items.

1. minimum of tensor
2. maximum of temsor
3. mean of a tensor
4. sum of a temsor

In [ ]:
A=tf.constant([-2,-44])
A

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -2, -44], dtype=int32)>

In [ ]:
tf.abs(A)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 2, 44], dtype=int32)>

In [ ]:
tf.math.reduce_min(A)

<tf.Tensor: shape=(), dtype=int32, numpy=-44>

In [ ]:
tf.math.reduce_max(A)

<tf.Tensor: shape=(), dtype=int32, numpy=-2>

In [ ]:
B=tf.constant([[2,4,5],[-5,1,7],[5,4,2]])
B

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  4,  5],
       [-5,  1,  7],
       [ 5,  4,  2]], dtype=int32)>

In [ ]:
tf.math.reduce_min(B)

<tf.Tensor: shape=(), dtype=int32, numpy=-5>

In [ ]:
tf.math.reduce_min(B,axis=0) # give each columns mininum number

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-5,  1,  2], dtype=int32)>

In [ ]:
tf.math.reduce_min(B,axis=1) # give each rows mininum number

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2, -5,  2], dtype=int32)>

In [ ]:
import numpy as np

In [ ]:
E=tf.constant(np.random.randint(0,100,size=20))
E

<tf.Tensor: shape=(20,), dtype=int64, numpy=
array([74, 71, 75, 55, 22, 91, 93, 52, 24, 17, 26, 23, 73, 31, 78, 37, 40,
       77, 86, 27])>

In [ ]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=20>, TensorShape([20]), 1)

In [ ]:
tf.math.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=17>

In [ ]:
tf.math.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=93>

In [ ]:
tf.math.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=53>

In [ ]:
tf.math.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1072>

In [ ]:
tf.math.reduce_variance(E)

TypeError: ignored

In [ ]:
F=tf.cast(E,tf.float16)

In [ ]:
tf.math.reduce_std(F)

<tf.Tensor: shape=(), dtype=float16, numpy=25.78>

In [ ]:
tf.math.reduce_variance(F)

<tf.Tensor: shape=(), dtype=float16, numpy=664.5>

### **find the positional maximum and minimum**

In [ ]:
tf.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=6>

In [ ]:
E

<tf.Tensor: shape=(20,), dtype=int64, numpy=
array([74, 71, 75, 55, 22, 91, 93, 52, 24, 17, 26, 23, 73, 31, 78, 37, 40,
       77, 86, 27])>

In [ ]:
E[tf.argmax(E)]

<tf.Tensor: shape=(), dtype=int64, numpy=93>

In [ ]:
tf.argmin(E)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [ ]:
E[tf.argmin(E)]

<tf.Tensor: shape=(), dtype=int64, numpy=17>

In [ ]:
B = tf.constant([[2, 20, 30, 3, 6], [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])
tf.math.argmax(B, 1) # along x-axis

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 2, 1])>

In [ ]:
B = tf.constant([[2, 20, 30, 3, 6], [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])
tf.math.argmax(B, 0) # along y-axis

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 2, 0, 2, 2])>

### **squeeze a tensor**

remove all 1-D axises

In [ ]:
F=tf.random.uniform([50])

In [ ]:
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

In [ ]:
tf.reshape(F,shape=(5,1,2,1,5))

<tf.Tensor: shape=(5, 1, 2, 1, 5), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396]],

         [[0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256]]]],



       [[[[0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ]],

         [[0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ]]]],



       [[[[0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ]],

         [[0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ]]]],



       [[[[0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784]],

         [[0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097]]]],



       [[[[0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176]],

         [[0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [ ]:
tf.squeeze(F)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

### **One hot Encoding**

In [ ]:
import tensorflow as tf

In [ ]:
some_list=[0,1,2,3,4,5,6]

tf.one_hot(some_list,depth=7)

<tf.Tensor: shape=(7, 7), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list,depth=7,on_value=True,off_value=False)

<tf.Tensor: shape=(7, 7), dtype=bool, numpy=
array([[ True, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False],
       [False, False,  True, False, False, False, False],
       [False, False, False,  True, False, False, False],
       [False, False, False, False,  True, False, False],
       [False, False, False, False, False,  True, False],
       [False, False, False, False, False, False,  True]])>

In [ ]:
C=tf.one_hot(some_list,depth=7,on_value='some cool',off_value='not x')

In [ ]:
C

<tf.Tensor: shape=(7, 7), dtype=string, numpy=
array([[b'some cool', b'not x', b'not x', b'not x', b'not x', b'not x',
        b'not x'],
       [b'not x', b'some cool', b'not x', b'not x', b'not x', b'not x',
        b'not x'],
       [b'not x', b'not x', b'some cool', b'not x', b'not x', b'not x',
        b'not x'],
       [b'not x', b'not x', b'not x', b'some cool', b'not x', b'not x',
        b'not x'],
       [b'not x', b'not x', b'not x', b'not x', b'some cool', b'not x',
        b'not x'],
       [b'not x', b'not x', b'not x', b'not x', b'not x', b'some cool',
        b'not x'],
       [b'not x', b'not x', b'not x', b'not x', b'not x', b'not x',
        b'some cool']], dtype=object)>

## **Tensorflow and NumPy's Compatibility**

* well compatiable with each other


In [ ]:
import numpy as np

In [ ]:
D=tf.constant(np.array([2.,3.4,5.6,1.]))
D

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([2. , 3.4, 5.6, 1. ])>

In [ ]:
D.numpy()

array([2. , 3.4, 5.6, 1. ])

In [ ]:
E=tf.constant([2.3,1.,4.,5.6])
E

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2.3, 1. , 4. , 5.6], dtype=float32)>

In [ ]:
E.dtype # 32 bit precision 


tf.float32

In [ ]:
D.dtype # 64 bit precision

tf.float64

## **Tensorflow connected to GPU**

In [ ]:
tf.config.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU')]

In [ ]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [ ]:
tf.test.is_built_with_gpu_support()

True

In [ ]:
tf.test.gpu_device_name()

''

* after configuration changes

In [ ]:
import tensorflow as tf

In [ ]:
tf.config.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU'),
 LogicalDevice(name='/device:GPU:0', device_type='GPU')]

In [ ]:
tf.test.gpu_device_name()

'/device:GPU:0'

In [ ]:
tf.test.is_built_with_cuda()

True

In [ ]:
!nvidia-smi

Fri Jan  7 10:38:24 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P0    60W / 149W |    144MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------